// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp.EF.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240314193244_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Mathmatics",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Physics",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Biology",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Chemistry",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "CS-50",
                            Price = 2000m
                        });
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Abdullah"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ahmed Fathi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Suliaman Ali"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Monzer Fares"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wael Saed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
