// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp.EF.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240315141206_add-sections")]
    partial class addsections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Mathmatics",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Physics",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Biology",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Chemistry",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "CS-50",
                            Price = 2000m
                        });
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FName = "Ahmed",
                            LName = " Abdullah",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            FName = "Ahmed",
                            LName = " Fathi",
                            OfficeId = 2
                        },
                        new
                        {
                            Id = 3,
                            FName = "Suliaman",
                            LName = "Ali",
                            OfficeId = 3
                        },
                        new
                        {
                            Id = 4,
                            FName = "Monzer",
                            LName = "Fares",
                            OfficeId = 4
                        },
                        new
                        {
                            Id = 5,
                            FName = "Wael",
                            LName = "Saed",
                            OfficeId = 5
                        });
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("OfficeLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OfficeLocation = "OfficeLocation #1",
                            OfficeName = "Office #1"
                        },
                        new
                        {
                            Id = 2,
                            OfficeLocation = "OfficeLocation #2",
                            OfficeName = "Office #2"
                        },
                        new
                        {
                            Id = 3,
                            OfficeLocation = "OfficeLocation #3",
                            OfficeName = "Office #3"
                        },
                        new
                        {
                            Id = 4,
                            OfficeLocation = "OfficeLocation #4",
                            OfficeName = "Office #4"
                        },
                        new
                        {
                            Id = 5,
                            OfficeLocation = "OfficeLocation #5",
                            OfficeName = "Office #5"
                        });
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Section");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            InstructorId = 1,
                            SectionName = "Section #1"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            InstructorId = 2,
                            SectionName = "Section #2"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            InstructorId = 3,
                            SectionName = "Section #3"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            InstructorId = 2,
                            SectionName = "Section #4"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            InstructorId = 3,
                            SectionName = "Section #5"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 4,
                            InstructorId = 4,
                            SectionName = "Section #6"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            InstructorId = 5,
                            SectionName = "Section #7"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            InstructorId = 5,
                            SectionName = "Section #8"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            InstructorId = 2,
                            SectionName = "Section #9"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 5,
                            InstructorId = 2,
                            SectionName = "Section #10"
                        });
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Instructor", b =>
                {
                    b.HasOne("ConsoleApp.EF.Migrations.Entities.Office", "Office")
                        .WithOne("Instructor")
                        .HasForeignKey("ConsoleApp.EF.Migrations.Entities.Instructor", "OfficeId");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Section", b =>
                {
                    b.HasOne("ConsoleApp.EF.Migrations.Entities.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp.EF.Migrations.Entities.Instructor", "Instructor")
                        .WithMany("Sections")
                        .HasForeignKey("InstructorId");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Instructor", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ConsoleApp.EF.Migrations.Entities.Office", b =>
                {
                    b.Navigation("Instructor");
                });
#pragma warning restore 612, 618
        }
    }
}
